### ISSUE TITLE
CRAN Submission Checklist

### ISSUE THREAD

**Issue by PhilBoileau** [insightsengineering/uniCATE#11]
- [ ] Add examples to all functions.
- [ ] Increase speed of tests by decreasing size of simulated testing datasets.
- [ ] Ensure that internal and external function references are properly formatted.
- [ ] Make `sl3` an "enhancement" instead of a dependency.
- [ ] Complete JOSS peer review.

**Comment by PhilBoileau** [comment]
Will not be moving forward with CRAN submission.
